"""Write test-output/ai/ci-summary.md (port of ci-summary-writer.ts) — suitable
for $GITHUB_STEP_SUMMARY, a Jenkins description, or a GitLab artifact preview.
"""

from __future__ import annotations

from pathlib import Path

from aiqa_framework.ai_qa_agent.schemas.failure_event import FailureEvent
from aiqa_framework.ai_qa_agent.utils.paths import ai_qa_out_dir
from aiqa_framework.ai_qa_agent.watchers.critical_pattern_detector import CriticalEvent


def write_ci_summary(run_id: str, failures: list[FailureEvent], criticals: list[CriticalEvent]) -> Path:
    finals = [f for f in failures if f.is_final_failure]
    lines = [f"## AI QA Agent — run `{run_id}`", ""]

    if not finals and not criticals:
        lines.append("✅ No final-attempt failures and no critical patterns detected.")
    else:
        lines.append(f"- **Final-attempt failures:** {len(finals)}")
        lines.append(f"- **Critical events:** {len(criticals)}")

    if criticals:
        lines += ["", "### 🚨 Critical events"]
        lines += [f"- `{c.trigger}` — {c.summary}" for c in criticals]

    if finals:
        lines += ["", "### Failing tests"]
        for f in finals[:20]:
            first = f.error_message.splitlines()[0] if f.error_message else "no message"
            lines.append(f"- **{f.title}** — `{f.file}` — {first}")
        if len(finals) > 20:
            lines.append(f"- _…and {len(finals) - 20} more (see test-output/ai/diagnosis.md)_")

    lines += ["", "_Generated by AI QA Agent (deterministic; no LLM call)._"]
    path = ai_qa_out_dir() / "ci-summary.md"
    path.write_text("\n".join(lines))
    return path
