"""EXAMPLE — a spec generated by the qa-agent skill.

Python port of ``sample-spec.ts``. Illustration only (lives under the skill,
not collected by pytest). Pairs with ``sample_page_object.py`` — in a real run
the qa-agent generates the Page Object into ``aiqa_framework/pages/login_page.py``.

Demonstrates the framework conventions:
  - import ``TAGS, tags, jira`` from ``aiqa_framework.shared.config.tags`` — the
    feature marker value EQUALS the Jira label (so ``-m <label>`` selects it)
  - decorate with ``@tags(...)`` for selection and ``@jira("KEY")`` so any bug
    raised on the final failed attempt links back to the parent user story
  - call the Page Object — never ``page.locator(...)`` in a spec
  - keep test data in a ``testdata/`` module, not inline
  - the ``page`` fixture is already authenticated (pytest-playwright + storage
    state); plain comments delimit the readable steps

Run::

    uv run pytest -m "regression and smoke"
"""

from __future__ import annotations

import os

from aiqa_framework.modules.ui.pages.login_page import LoginPage

from aiqa_framework.shared.config.tags import TAGS, jira, tags


@tags(TAGS.REGRESSION, TAGS.SMOKE, TAGS.P0)
@jira("PROJ-1")  # <- parent user story key
def test_login_with_valid_credentials(page) -> None:
    login = LoginPage(page)

    # Open the sign-in page.
    login.open(os.environ.get("AUTH_URL", "/signin"))

    # Sign in with a valid account.
    login.sign_in(
        os.environ.get("APP_USER", "tester@example.com"),
        os.environ.get("APP_PASS", "YOUR_PASSWORD"),
    )

    # Verify the user is signed in.
    login.verify_signed_in()
