"""EXAMPLE — a Page Object generated by the qa-agent skill.

Python port of ``sample-page-object.ts``. Illustration only (lives under the
skill, not collected by pytest). Pairs with ``sample_spec.py``.

Demonstrates the framework conventions:
  - ``extends BasePage`` (gives ``self.page`` and ``self.keyword``)
  - selectors grouped as class attributes
  - every interaction goes through ``self.keyword.*`` — never call
    ``self.page.locator(...)`` directly in a Page Object
  - prefer test-only attributes (ActionKeyword priority:
    ``data-zcqa -> data-test-id -> data-id -> data-title``)
"""

from __future__ import annotations

from aiqa_framework.core.base_page import BasePage


class LoginPage(BasePage):
    _email_input = '[data-test-id="email"]'
    _password_input = '[data-test-id="password"]'
    _submit_button = 'button[type="submit"]'
    _error_banner = '[data-test-id="login-error"]'
    _avatar = '[data-test-id="user-avatar"]'

    def open(self, url: str) -> None:
        self.keyword.goto(url)

    def sign_in(self, email: str, password: str) -> None:
        self.keyword.wait_and_fill(self._email_input, email)
        self.keyword.wait_and_fill(self._password_input, password)
        self.keyword.wait_and_click(self._submit_button)

    def verify_signed_in(self) -> None:
        self.keyword.verify_element_visible(
            self._avatar,
            reason="Expected the user avatar after a successful sign-in",
        )

    def get_error_message(self) -> str:
        return self.keyword.get_element_text(self._error_banner)
