#!/usr/bin/env python3
"""create_gitlab_mr.py — open a GitLab merge request for a pushed branch
(the ship step: generated code reaches the team via branch + MR).

Usage:
  python3 .claude/skills/qa-agent/scripts/create_gitlab_mr.py \
    --source test/EAST-123-login \
    --title  "EAST-123: Login — qa-agent generated tests" \
    [--target master] \
    [--description-file test-output/ai/mr-description.md]

Branch naming (team rule): test/<STORY-KEY>-<feature-slug> for story-driven
runs; test/manual-<feature-slug>-<YYYYMMDD> for gen-auto-test runs without a
story.

Config: GITLAB_URL, GITLAB_TOKEN, GITLAB_PROJECT_ID env vars, falling back to
environments/.env.gitlab (gitignored; copy environments/.env.gitlab.example).

Exit codes: 0 = MR created (URL printed), 1 = config missing, 2 = usage error,
3 = GitLab API error. Stdlib only.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path


def find_repo_root(start: Path) -> Path:
    for d in (start, *start.parents):
        if (d / "pyproject.toml").is_file():
            return d
    return Path.cwd()


def load_config() -> dict[str, str]:
    import os

    cfg = {k: os.environ.get(k, "") for k in ("GITLAB_URL", "GITLAB_TOKEN", "GITLAB_PROJECT_ID")}
    env_file = find_repo_root(Path(__file__).resolve()) / "environments" / ".env.gitlab"
    if env_file.is_file():
        for line in env_file.read_text(encoding="utf-8").splitlines():
            m = re.match(r"^\s*([A-Z_]+)\s*=\s*(.*?)\s*$", line)
            if m and not cfg.get(m.group(1)):
                cfg[m.group(1)] = m.group(2).strip("\"'")
    cfg["GITLAB_URL"] = cfg["GITLAB_URL"].rstrip("/")
    return cfg


def main() -> int:
    parser = argparse.ArgumentParser(description="Open a GitLab MR for a pushed branch.")
    parser.add_argument("--source", required=True, help="Source branch (already pushed)")
    parser.add_argument("--title", required=True)
    parser.add_argument("--target", default="master")
    parser.add_argument("--description-file", default="")
    args = parser.parse_args()

    cfg = load_config()
    if not (cfg["GITLAB_URL"] and cfg["GITLAB_TOKEN"] and cfg["GITLAB_PROJECT_ID"]):
        print(
            "GitLab config missing — set GITLAB_URL + GITLAB_TOKEN + GITLAB_PROJECT_ID env vars "
            "or fill environments/.env.gitlab. No MR was created.",
            file=sys.stderr,
        )
        return 1

    description_path = Path(args.description_file) if args.description_file else None
    description = (
        description_path.read_text(encoding="utf-8")
        if description_path and description_path.is_file()
        else "Generated by the qa-agent skill. See docs/ai/<module>/memory.md for the run context."
    )

    project = urllib.parse.quote(cfg["GITLAB_PROJECT_ID"], safe="")
    request = urllib.request.Request(
        f"{cfg['GITLAB_URL']}/api/v4/projects/{project}/merge_requests",
        data=json.dumps(
            {
                "source_branch": args.source,
                "target_branch": args.target,
                "title": args.title,
                "description": description,
                "remove_source_branch": True,
            }
        ).encode(),
        method="POST",
        headers={"PRIVATE-TOKEN": cfg["GITLAB_TOKEN"], "Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(request, timeout=60) as response:  # noqa: S310
            mr = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as err:
        detail = err.read().decode("utf-8", "replace")[:500]
        print(f"GitLab MR creation failed: HTTP {err.code} — {detail}", file=sys.stderr)
        return 3
    except Exception as err:  # noqa: BLE001
        print(f"Unexpected error: {err}", file=sys.stderr)
        return 3

    print(f"MR created: {mr['web_url']} ({args.source} -> {args.target})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
