"""GameClient — the single gRPC interaction layer (port of game-client.ts).

Requires generated stubs: run ``poe proto-gen`` first. Best practices: a
deadline on every call, bearer-token metadata auth, and helpers for all four
RPC types. Errors raise ``grpc.RpcError`` so specs assert ``err.code()``.
"""

from __future__ import annotations

from collections.abc import Iterable

import grpc

from aiqa_framework.grpc import generated as _gen  # noqa: F401  (puts stubs on sys.path)

import game_pb2  # type: ignore  # noqa: E402  (generated by poe proto-gen)
import game_pb2_grpc  # type: ignore  # noqa: E402


class GameClient:
    def __init__(
        self,
        host: str = "localhost",
        port: int = 50051,
        tls: bool = False,
        token: str | None = None,
        default_deadline: float = 5.0,
    ) -> None:
        target = f"{host}:{port}"
        if tls:
            self._channel = grpc.secure_channel(target, grpc.ssl_channel_credentials())
        else:
            self._channel = grpc.insecure_channel(target)
        self._stub = game_pb2_grpc.GameServiceStub(self._channel)
        self._token = token
        self._deadline = default_deadline

    def wait_for_ready(self, timeout: float = 5.0) -> None:
        grpc.channel_ready_future(self._channel).result(timeout=timeout)

    def _meta(self, token: str | None = None) -> list[tuple[str, str]]:
        t = token if token is not None else self._token
        return [("authorization", f"Bearer {t}")] if t else []

    def _to(self, deadline: float | None) -> float:
        return deadline if deadline is not None else self._deadline

    # ---- unary ----
    def get_balance(self, player_id: str, deadline: float | None = None, token: str | None = None):
        return self._stub.GetBalance(
            game_pb2.GetBalanceRequest(player_id=player_id),
            timeout=self._to(deadline),
            metadata=self._meta(token),
        )

    def place_bet(self, player_id: str, round_id: str, amount: int, market: str,
                  deadline: float | None = None, token: str | None = None):
        return self._stub.PlaceBet(
            game_pb2.PlaceBetRequest(player_id=player_id, round_id=round_id, amount=amount, market=market),
            timeout=self._to(deadline),
            metadata=self._meta(token),
        )

    # ---- server-streaming ----
    def stream_game_state(self, table_id: str, deadline: float | None = None) -> list:
        return list(
            self._stub.StreamGameState(
                game_pb2.StreamGameStateRequest(table_id=table_id),
                timeout=self._to(deadline),
                metadata=self._meta(),
            )
        )

    # ---- client-streaming ----
    def send_actions(self, actions: Iterable[dict], deadline: float | None = None):
        def gen():
            for a in actions:
                yield game_pb2.PlayerAction(**a)

        return self._stub.SendActions(gen(), timeout=self._to(deadline), metadata=self._meta())

    # ---- bidirectional ----
    def play_live(self, actions: Iterable[dict], deadline: float | None = None) -> list:
        def gen():
            for a in actions:
                yield game_pb2.PlayerAction(**a)

        return list(self._stub.PlayLive(gen(), timeout=self._to(deadline), metadata=self._meta()))

    def close(self) -> None:
        self._channel.close()
